version: "2.2"
services:
  jobmanager:
    build: .
    image: varimat-stream-processing:1.3
    hostname: jobmanager
    container_name: jobmanager
    ports:
      - "8081:8080"
#    command: java -Xms10g -Xmx28g -jar /usr/local/lib/varimat-stream-processing-1.3.jar
    command: standalone-job --job-classname org.varimat.com.EMPADStreamCommand
    volumes:
      - ./output:/empad/output
      - ./calibration:/empad/calibration/
    environment:
      - EMPAD_HOME=${EMPAD_HOME:-/empad}
      - KAFKA_ENV_USERNAME=${KAFKA_ENV_USERNAME}
      - KAFKA_ENV_PASSWORD=${KAFKA_ENV_PASSWORD}
      - EMPAD_TOPIC=${EMPAD_TOPIC}
      - GROUP_ID=${GROUP_ID}
      - CHECKPOINT_STORAGE=${CHECKPOINT_STORAGE}
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        parallelism.default: 2        

  taskmanager:
    build: .
    image: varimat-stream-processing:1.3
    hostname: taskmanager
    container_name: taskmanager
    depends_on:
      - jobmanager
    command: taskmanager
    volumes:
      - ./output:/empad/output
      - ./calibration:/empad/calibration
    environment:
      - EMPAD_HOME=${EMPAD_HOME:-/empad}
      - KAFKA_ENV_USERNAME=${KAFKA_ENV_USERNAME}
      - KAFKA_ENV_PASSWORD=${KAFKA_ENV_PASSWORD}
      - EMPAD_TOPIC=${EMPAD_TOPIC}
      - GROUP_ID=${GROUP_ID}
      - CHECKPOINT_STORAGE=${CHECKPOINT_STORAGE}
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 4
        parallelism.default: 2
